# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExpertMode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  database ="tubes_pbo"
)
mycursor = mydb.cursor()


class Ui_ExpertMode(object):
    def setupUi(self, ExpertMode):
        ExpertMode.setObjectName("ExpertMode")
        ExpertMode.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ExpertMode)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 70, 681, 441))
        self.groupBox.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(160, 30, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 100, 579, 281))
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.Execute = QtWidgets.QPushButton(self.groupBox_2)
        self.Execute.setGeometry(QtCore.QRect(360, 240, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Execute.sizePolicy().hasHeightForWidth())
        self.Execute.setSizePolicy(sizePolicy)
        self.Execute.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.Execute.setAutoDefault(False)
        self.Execute.setDefault(False)
        self.Execute.setFlat(False)
        self.Execute.setObjectName("Execute")
        self.Back = QtWidgets.QPushButton(self.groupBox_2)
        self.Back.setGeometry(QtCore.QRect(460, 240, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.Back.setAutoDefault(False)
        self.Back.setDefault(False)
        self.Back.setFlat(False)
        self.Back.setObjectName("Back")
        self.Command = QtWidgets.QLineEdit(self.groupBox_2)
        self.Command.setGeometry(QtCore.QRect(30, 50, 521, 171))
        self.Command.setStyleSheet("background-color: rgb(255, 255, 215);")
        self.Command.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Command.setObjectName("Command")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.label_2.setObjectName("label_2")
        ExpertMode.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ExpertMode)
        self.statusbar.setObjectName("statusbar")
        ExpertMode.setStatusBar(self.statusbar)

        self.retranslateUi(ExpertMode)
        QtCore.QMetaObject.connectSlotsByName(ExpertMode)
        #code here
        self.Execute.clicked.connect(self.Eksekusi)

    def retranslateUi(self, ExpertMode):
        _translate = QtCore.QCoreApplication.translate
        ExpertMode.setWindowTitle(_translate("ExpertMode", "ExpertMode"))
        self.label.setText(_translate("ExpertMode", "<html><head/><body><p><span style=\" font-size:26pt;\">Mode Expert</span></p></body></html>"))
        self.Execute.setText(_translate("ExpertMode", "Execute"))
        self.Back.setText(_translate("ExpertMode", "Back"))
        self.Command.setPlaceholderText(_translate("ExpertMode", "Command;"))
        self.label_2.setText(_translate("ExpertMode", "Your Command  :"))

    def Eksekusi(self):
        perintah = str(self.Command.text())
        if perintah:
            try:
                mycursor.execute(perintah)
                result = mycursor.fetchall()
                mydb.commit()

                if result:
                    #result to Text
                    text = ''
                    for i in result:
                        for j in i:
                            text = text + str(j)+'\t'
                        text = text + '\n'
                    self.show_Popup(text)

            except mysql.connector.Error as error:
                self.show_Popup(f'Gagal Mengeksekusi perintah\nError Code\n{error}')

    def show_Popup(self,message):
        msg = QMessageBox()
        msg.setWindowTitle("Login info")
        msg.setText(message)
        x = msg.exec_()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExpertMode = QtWidgets.QMainWindow()
    ui = Ui_ExpertMode()
    ui.setupUi(ExpertMode)
    ExpertMode.show()
    sys.exit(app.exec_())
