# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Akun.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import BuatAkun, PilihUser
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  database ="tubes_pbo"
)
mycursor = mydb.cursor()


class Ui_KelolaAkun(object):
    def setupUi(self, KelolaAkun):
        KelolaAkun.setObjectName("KelolaAkun")
        KelolaAkun.resize(800, 600)
        KelolaAkun.setStyleSheet("background-color: rgb(255, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(KelolaAkun)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 741, 541))
        self.widget.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/BackIcon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.BackButton = QtWidgets.QPushButton(self.widget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.BackButton.setStyleSheet("background-color: transparent;")
        self.BackButton.setText("")
        self.BackButton.setObjectName("BackButton")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 60, 661, 381))
        self.tableWidget.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(60, 450, 661, 81))
        self.frame.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(370, 10, 211, 61))
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 255);\n"
"border-radius : 10px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 10, 211, 61))
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 255);\n"
"border-radius : 10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        KelolaAkun.setCentralWidget(self.centralwidget)

        self.retranslateUi(KelolaAkun)
        QtCore.QMetaObject.connectSlotsByName(KelolaAkun)

        #code here
        self.pushButton_2.clicked.connect(lambda:self.Buatin(KelolaAkun))
        self.pushButton.clicked.connect(lambda:self.Hapusin(KelolaAkun))

    def retranslateUi(self, KelolaAkun):
        _translate = QtCore.QCoreApplication.translate
        KelolaAkun.setWindowTitle(_translate("KelolaAkun", "Kelola Akun"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("KelolaAkun", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("KelolaAkun", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("KelolaAkun", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("KelolaAkun", "username"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("KelolaAkun", "Password"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("KelolaAkun", "Tipe_Akun"))
        self.pushButton.setText(_translate("KelolaAkun", "Hapus Akun"))
        self.pushButton_2.setText(_translate("KelolaAkun", "Buat Akun"))

    def setUpin(self):
        order = "select * from login_info"
        try:
            mycursor.execute(order)
            data = mycursor.fetchall()
            if not data:
                self.tableWidget.setColumnCount(1)
                self.tableWidget.setRowCount(1)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setItem(0, 0, item)
                item = self.tableWidget.item(0, 0)
                item.setText("NULL")
                self.show_Popup("Daftar akun tidak ditemukan!")
            else:
                self.tableWidget.setRowCount(len(data))
                ci=0
                for i in data:
                    cj=0
                    for j in i:
                        item = QtWidgets.QTableWidgetItem()
                        self.tableWidget.setItem(ci, cj, item)
                        item = self.tableWidget.item(ci,cj)
                        item.setText(j)
                        cj+=1
                    ci+=1

        except mysql.connector.Error as error:
            self.show_Popup(f'Galat!\nError Code\n{error}')

    def Buatin(self, KelolaAkun):
        self.MenuAkun = QtWidgets.QMainWindow()
        self.ui = BuatAkun.Ui_BuatAkun()
        self.ui.setupUi(self.MenuAkun)
        self.MenuAkun.show()
        KelolaAkun.hide()
        self.ui.BackButton.clicked.connect(lambda: self.RiseMeUp(KelolaAkun))

    def Hapusin(self, KelolaAkun):
        self.MenuAkun = QtWidgets.QMainWindow()
        self.ui = PilihUser.Ui_PilihUsername()
        self.ui.setupUi(self.MenuAkun)
        self.ui.setUpin()
        self.MenuAkun.show()
        # KelolaAkun.hide()
        self.ui.Ruang.clicked.connect(lambda: self.Hapuslah())

    def Hapuslah(self):
        UN = self.ui.comboBox.currentText()
        if UN == "-Pilih Username-":
            self.show_Popup("Harap pilih username terlebih dahulu!")
            return 0
        order = f"delete from login_info where login_info.username = '{UN}'"
        try:
            mycursor.execute(order)
            mydb.commit()
            self.show_Popup(f"Akun {UN} berhasil dihapus!")

        except mysql.connector.Error as error:
            self.show_Popup(f'Galat!\nError Code:\n{error}')

        self.MenuAkun.hide()
        self.setUpin()

    def RiseMeUp(self, KelolaAkun):
        self.MenuAkun.hide()
        mydb.commit()
        self.setUpin()
        KelolaAkun.show()

    def show_Popup(self,message):
        msg = QMessageBox()
        msg.setWindowTitle("Info")
        msg.setText(message)
        x = msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KelolaAkun = QtWidgets.QMainWindow()
    ui = Ui_KelolaAkun()
    ui.setupUi(KelolaAkun)
    ui.setUpin()
    KelolaAkun.show()
    sys.exit(app.exec_())
