# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Peminjaman.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QMessageBox
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  database ="tubes_pbo"
)
mycursor = mydb.cursor()

def convertToBinaryData(filename):
    # Convert digital data to binary format
    with open(filename, 'rb') as file:
        binaryData = file.read()
    return binaryData

def convertdate(tanggal):
    idx1 = tanggal.find('/')
    bulan = tanggal[0:idx1]
    if (len(bulan)!=2):
        bulan = '0'+bulan
    idx2 = tanggal.find('/',idx1+1)
    hari = tanggal[idx1+1:idx2]
    if (len(hari)!=2):
        hari = '0'+hari
    tahun = tanggal[idx2+1:]
    return f'{tahun}-{bulan}-{hari}'

class Ui_Peminjaman(object):
    def setupUi(self, Peminjaman):
        Peminjaman.setObjectName("Peminjaman")
        Peminjaman.resize(800, 600)
        Peminjaman.setStyleSheet("background-color: rgb(255, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(Peminjaman)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 80, 681, 441))
        self.groupBox.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(150, 20, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(60, 90, 571, 331))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 551, 280))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.No_Surat = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.No_Surat.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.No_Surat.setText("")
        self.No_Surat.setClearButtonEnabled(False)
        self.No_Surat.setObjectName("No_Surat")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.No_Surat)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.NIP = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.NIP.setEnabled(True)
        self.NIP.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.NIP.setInputMethodHints(QtCore.Qt.ImhTime)
        self.NIP.setText("")
        self.NIP.setClearButtonEnabled(False)
        self.NIP.setObjectName("NIP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.NIP)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ID_Barang = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ID_Barang.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.ID_Barang.setText("")
        self.ID_Barang.setClearButtonEnabled(False)
        self.ID_Barang.setObjectName("ID_Barang")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ID_Barang)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.Tgl_Peminjaman = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.Tgl_Peminjaman.setKeyboardTracking(True)
        self.Tgl_Peminjaman.setProperty("showGroupSeparator", False)
        self.Tgl_Peminjaman.setCalendarPopup(True)
        self.Tgl_Peminjaman.setObjectName("Tgl_Peminjaman")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Tgl_Peminjaman)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Tgl_Pengembalian = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.Tgl_Pengembalian.setCalendarPopup(True)
        self.Tgl_Pengembalian.setObjectName("Tgl_Pengembalian")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Tgl_Pengembalian)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.Pilih_Gedung = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.Pilih_Gedung.setFont(font)
        self.Pilih_Gedung.setObjectName("Pilih_Gedung")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Pilih_Gedung)
        self.No_Ruangan = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.No_Ruangan.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.No_Ruangan.setText("")
        self.No_Ruangan.setClearButtonEnabled(False)
        self.No_Ruangan.setObjectName("No_Ruangan")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.No_Ruangan)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.FindDirectory = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.FindDirectory.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.FindDirectory.setObjectName("FindDirectory")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.FindDirectory)
        self.DirectoryFinderButton = QtWidgets.QToolButton(self.formLayoutWidget)
        self.DirectoryFinderButton.setObjectName("DirectoryFinderButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.DirectoryFinderButton)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.Jumlah_Barang = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Jumlah_Barang.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.Jumlah_Barang.setText("")
        self.Jumlah_Barang.setClearButtonEnabled(False)
        self.Jumlah_Barang.setObjectName("Jumlah_Barang")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Jumlah_Barang)
        self.Input = QtWidgets.QPushButton(self.frame)
        self.Input.setGeometry(QtCore.QRect(470, 300, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input.sizePolicy().hasHeightForWidth())
        self.Input.setSizePolicy(sizePolicy)
        self.Input.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.Input.setAutoDefault(False)
        self.Input.setDefault(False)
        self.Input.setFlat(False)
        self.Input.setObjectName("Input")
        self.BackButton = QtWidgets.QPushButton(self.groupBox)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setKerning(False)
        self.BackButton.setFont(font)
        self.BackButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BackButton.setMouseTracking(False)
        self.BackButton.setAutoFillBackground(False)
        self.BackButton.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: transparent;\n"
"")
        self.BackButton.setText("")
        self.BackButton.setObjectName("BackButton")
        self.BackIcon = QtWidgets.QLabel(self.groupBox)
        self.BackIcon.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.BackIcon.setText("")
        self.BackIcon.setPixmap(QtGui.QPixmap("icon/BackIcon.png"))
        self.BackIcon.setScaledContents(True)
        self.BackIcon.setObjectName("BackIcon")
        self.label.raise_()
        self.frame.raise_()
        self.BackIcon.raise_()
        self.BackButton.raise_()
        Peminjaman.setCentralWidget(self.centralwidget)

        self.retranslateUi(Peminjaman)
        QtCore.QMetaObject.connectSlotsByName(Peminjaman)

        #code here


    def retranslateUi(self, Peminjaman):
        _translate = QtCore.QCoreApplication.translate
        Peminjaman.setWindowTitle(_translate("Peminjaman", "Peminjaman"))
        self.label.setText(_translate("Peminjaman", "Form Peminjaman"))
        self.label_2.setText(_translate("Peminjaman", "No. Surat"))
        self.No_Surat.setPlaceholderText(_translate("Peminjaman", "No. Surat Peminjaman"))
        self.label_3.setText(_translate("Peminjaman", "NIP"))
        self.NIP.setPlaceholderText(_translate("Peminjaman", "NIP"))
        self.label_4.setText(_translate("Peminjaman", "ID_Barang"))
        self.ID_Barang.setPlaceholderText(_translate("Peminjaman", "ID_Barang"))
        self.label_6.setText(_translate("Peminjaman", "Tanggal Peminjaman"))
        self.label_7.setText(_translate("Peminjaman", "Tanggal Pengembalian"))
        self.label_8.setText(_translate("Peminjaman", "Lokasi Barang"))
        self.Pilih_Gedung.setCurrentText(_translate("Peminjaman", "- Pilih Gedung -"))
        self.Pilih_Gedung.setItemText(0, _translate("Peminjaman", "- Pilih Gedung -"))
        self.Pilih_Gedung.setItemText(1, _translate("Peminjaman", "A"))
        self.Pilih_Gedung.setItemText(2, _translate("Peminjaman", "B"))
        self.Pilih_Gedung.setItemText(3, _translate("Peminjaman", "C"))
        self.Pilih_Gedung.setItemText(4, _translate("Peminjaman", "D"))
        self.Pilih_Gedung.setItemText(5, _translate("Peminjaman", "E"))
        self.Pilih_Gedung.setItemText(6, _translate("Peminjaman", "F"))
        self.Pilih_Gedung.setItemText(7, _translate("Peminjaman", "GKU"))
        self.Pilih_Gedung.setItemText(8, _translate("Peminjaman", "Labtek1"))
        self.Pilih_Gedung.setItemText(9, _translate("Peminjaman", "Labtek2"))
        self.Pilih_Gedung.setItemText(10, _translate("Peminjaman", "Labtek3"))
        self.No_Ruangan.setPlaceholderText(_translate("Peminjaman", "Nomor Ruang"))
        self.label_5.setText(_translate("Peminjaman", "Scan BAST"))
        self.FindDirectory.setPlaceholderText(_translate("Peminjaman", "File Directory"))
        self.DirectoryFinderButton.setText(_translate("Peminjaman", "..."))
        self.label_9.setText(_translate("Peminjaman", "Jumlah Barang"))
        self.Jumlah_Barang.setPlaceholderText(_translate("Peminjaman", "Jumlah Barang"))
        self.Input.setText(_translate("Peminjaman", "Input"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Peminjaman = QtWidgets.QMainWindow()
    ui = Ui_Peminjaman()
    ui.setupUi(Peminjaman)
    Peminjaman.show()
    sys.exit(app.exec_())
