# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tampil.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  database ="tubes_pbo"
)
mycursor = mydb.cursor()


class Ui_Tampilkan(object):
    def setupUi(self, Tampilkan):
        Tampilkan.setObjectName("Tampilkan")
        Tampilkan.resize(800, 600)
        Tampilkan.setStyleSheet("background-color: rgb(255, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(Tampilkan)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 741, 541))
        self.widget.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/BackIcon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.BackButton = QtWidgets.QPushButton(self.widget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.BackButton.setStyleSheet("background-color: transparent;")
        self.BackButton.setText("")
        self.BackButton.setObjectName("BackButton")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 90, 661, 421))
        self.tableWidget.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        self.Judul = QtWidgets.QLabel(self.widget)
        self.Judul.setGeometry(QtCore.QRect(140, 20, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Judul.setFont(font)
        self.Judul.setAlignment(QtCore.Qt.AlignCenter)
        self.Judul.setObjectName("Judul")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(60, 90, 641, 391))
        self.frame.setStyleSheet("background-color: transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        Tampilkan.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tampilkan)
        QtCore.QMetaObject.connectSlotsByName(Tampilkan)

    def setUpin(self,Judul,Loc):
        self.Judul.setText(f"DATA INVENTARIS {Judul}")
        self.Loc = Loc

    def retranslateUi(self, Tampilkan):
        _translate = QtCore.QCoreApplication.translate
        Tampilkan.setWindowTitle(_translate("Tampilkan", "Data Inventaris"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Tampilkan", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Tampilkan", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Tampilkan", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Tampilkan", "ID Peminjaman"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Tampilkan", "NIP Peminjam"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Tampilkan", "ID Barang"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Tampilkan", "Lokasi"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Tampilkan", "Gedung"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Tampilkan", "!ID"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Tampilkan", "!NIP"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Tampilkan", "!IDB"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Tampilkan", "!Lok"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Tampilkan", "!Gedu"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Tampilkan", "@ID"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Tampilkan", "@NIP"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Tampilkan", "@DB"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Tampilkan", "@Lok"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("Tampilkan", "@Gedu"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Tampilkan", "#ID"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Tampilkan", "#NIP"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Tampilkan", "#DB"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Tampilkan", "#Lok"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Tampilkan", "#Gedu"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.Judul.setText(_translate("Tampilkan", "DATA INVENTARIS ......"))

    def setUpin(self,Judul,Loc):
        self.Judul.setText(f"DATA INVENTARIS {Judul}")
        self.Loc = Loc

        if Judul == "GEDUNG":
            order = f"""select ID_Peminjaman,ID_Peminjam,ID_Barang,Gedung,No_Ruangan
                    from gedung right outer join peminjaman on peminjaman.gedung = gedung.Kode_Gedung
                    where Nama_Gedung = '{Loc}'"""
        if Judul == "RUANG":
            order = f"""select ID_Peminjaman,ID_Peminjam,ID_Barang,Gedung,peminjaman.No_Ruangan
                    from ruangan right outer join peminjaman on peminjaman.No_Ruangan = ruangan.No_Ruangan
                    where ruangan.No_Ruangan = '{Loc}'"""
        try:
            mycursor.execute(order)
            data = mycursor.fetchall()
            if not data:
                self.tableWidget.setColumnCount(1)
                self.tableWidget.setRowCount(1)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setHorizontalHeaderItem(0, item)
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setItem(0, 0, item)
                item = self.tableWidget.item(0, 0)
                item.setText("NULL")
                self.show_Popup("Tidak terdapat data inventaris apapun di lokasi ini!")
            else:
                self.tableWidget.setRowCount(len(data))
                ci=0
                for i in data:
                    cj=0
                    for j in i:
                        item = QtWidgets.QTableWidgetItem()
                        self.tableWidget.setItem(ci, cj, item)
                        item = self.tableWidget.item(ci,cj)
                        item.setText(j)
                        cj+=1
                    ci+=1

        except mysql.connector.Error as error:
            self.show_Popup(f'Galat!\nError Code\n{error}')

    def show_Popup(self,message):
        msg = QMessageBox()
        msg.setWindowTitle("Login info")
        msg.setText(message)
        x = msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tampilkan = QtWidgets.QMainWindow()
    ui = Ui_Tampilkan()
    ui.setupUi(Tampilkan)
    ui.setUpin("GEDUNG","Gedung D")
    Tampilkan.show()
    sys.exit(app.exec_())
